name: Gitflow Hotfix

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Gitflow action to perform'
        required: true
        type: choice
        options:
          - hotfix-start
          - hotfix-finish
      version:
        description: 'Hotfix version (for hotfix-start and hotfix-finish, e.g., 1.17.1)'
        required: false
        type: string
      branch:
        description: 'Hotfix branch name (for hotfix-finish, e.g., hotfix/1.17.1)'
        required: false
        type: string

jobs:
  gitflow-hotfix:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Configure Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    
    - name: Hotfix Start
      if: inputs.action == 'hotfix-start'
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          mvn gitflow:hotfix-start -B
        else
          mvn gitflow:hotfix-start -B -DhotfixVersion=${{ inputs.version }}
        fi
    
    - name: Hotfix Finish
      if: inputs.action == 'hotfix-finish'
      run: |
        if [ -n "${{ inputs.branch }}" ]; then
          mvn gitflow:hotfix-finish -B -DpushRemote=true -DhotfixBranch=${{ inputs.branch }}
        elif [ -n "${{ inputs.version }}" ]; then
          mvn gitflow:hotfix-finish -B -DpushRemote=true -DhotfixVersion=${{ inputs.version }}
        else
          echo "Error: Either branch or version must be specified for hotfix-finish"
          exit 1
        fi