name: Gitflow Release

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Gitflow action to perform'
        required: true
        type: choice
        options:
          - release-start
          - release-finish
      version:
        description: 'Release version (for release-start and release-finish, e.g., 1.18.0)'
        required: false
        type: string
      branch:
        description: 'Release branch name (REQUIRED for release-finish, e.g., release/1.18.0)'
        required: false
        type: string

jobs:
  gitflow-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Configure Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    
    - name: Release Start
      if: inputs.action == 'release-start'
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          mvn gitflow:release-start -B -ntp
        else
          mvn gitflow:release-start -B -ntp -DreleaseVersion=${{ inputs.version }}
        fi
    
    - name: Release Finish
      if: inputs.action == 'release-finish'
      run: |
        # For release-finish, we need to determine the branch
        if [ -n "${{ inputs.branch }}" ]; then
          echo "Using provided branch: ${{ inputs.branch }}"
          mvn gitflow:release-finish -B -ntp -DpushRemote=true -DreleaseBranch=${{ inputs.branch }}
        elif [ -n "${{ inputs.version }}" ]; then
          echo "Using provided version: ${{ inputs.version }}"
          mvn gitflow:release-finish -B -ntp -DpushRemote=true -DreleaseVersion=${{ inputs.version }}
        else
          # Try to detect current branch if on a release branch
          CURRENT_BRANCH=$(git branch --show-current)
          if [[ "$CURRENT_BRANCH" == release/* ]]; then
            echo "Auto-detected release branch: $CURRENT_BRANCH"
            mvn gitflow:release-finish -B -ntp -DpushRemote=true -DreleaseBranch=$CURRENT_BRANCH
          else
            echo "Error: Cannot auto-detect release branch. Either 'branch' or 'version' must be specified for release-finish."
            echo "Current branch: $CURRENT_BRANCH"
            echo "Please provide either:"
            echo "  - branch: The full release branch name (e.g., release/1.18.0)"
            echo "  - version: The version number (e.g., 1.18.0)"
            exit 1
          fi
        fi